CREATE TABLE CDT(
   id INTEGER
);

SELECT * FROM LIB$DDL_ChangeDataType('CDT', 'ID', 'SMALLINT', 0);

SELECT * FROM LIB$DDL_ChangeDataType('CDT', 'ID', 'SMALLINT', 1);

SHOW TABLE CDT;
COMMIT;

RECREATE TABLE CDT(
   id INTEGER
);

SET TERM ^;

CREATE TRIGGER CDT FOR CDT BEFORE INSERT AS
BEGIN
  new.id = new.id + 1; 
END
^

CREATE PROCEDURE CDT_P RETURNS(Summary INTEGER) AS
BEGIN
  Summary = (SELECT SUM(id) FROM CDT);
  SUSPEND;
END
^
SET TERM ;^
COMMIT;

INSERT INTO CDT(id) VALUES(2);
COMMIT;

SELECT * FROM CDT_P;   -- Procedure works

SELECT * FROM LIB$DDL_ChangeDataType('CDT', 'ID', 'SMALLINT', 0, 1);

SELECT * FROM LIB$DDL_ChangeDataType('CDT', 'ID', 'SMALLINT', 1, 1);
COMMIT;

SHOW TABLE CDT;
INSERT INTO CDT(id) VALUES(3);
SELECT * FROM CDT_P;   -- Check that procedure works

