-- Test REPL$DLL functionalisties

CREATE TABLE dll_test(a INTEGER UNIQUE);
COMMIT;

SET TERM ^;

EXECUTE BLOCK
AS
BEGIN
  INSERT INTO REPL$DDL(sql) VALUES('INSERT INTO dll_test VALUES(1);');
  INSERT INTO REPL$DDL(sql) VALUES('INSERT INTO dll_test VALUES(2);');
  INSERT INTO REPL$DDL(sql) VALUES('INSERT INTO dll_test VALUES(3);');
END
^
COMMIT^
EXECUTE BLOCK
AS
BEGIN
  IF((SELECT COUNT(*) FROM dll_test)<>3)THEN EXCEPTION LIB$DDL_Exception 'Test REPL$DLL failed';
END
^

DELETE FROM dll_test^
COMMIT^

EXECUTE BLOCK
AS
BEGIN
  INSERT INTO REPL$DDL(sql) VALUES('INSERT INTO dll_test VALUES(1);');
  INSERT INTO REPL$DDL(sql) VALUES('INSERT INTO dll_test VALUES(2);');
  BEGIN
    INSERT INTO REPL$DDL(sql) VALUES('INSERT INTO dll_test VALUES(''AA'');');
  WHEN ANY DO BEGIN END
  END
END
^

ROLLBACK^

EXECUTE BLOCK
AS
BEGIN
  IF((SELECT COUNT(*) FROM dll_test)>0)THEN EXCEPTION LIB$DDL_Exception 'Test REPL$DLL failed';
END
^
COMMIT^

EXECUTE BLOCK RETURNS(msg VARCHAR(50))
AS
DECLARE ds VARCHAR(1000);
DECLARE id INTEGER;
BEGIN
  id = -100;
  ds = 'INSERT INTO REPL$DDL(id, TimeOut, sql) VALUES('||id||', 20, ''INSERT INTO dll_test VALUES(1);'')';
  EXECUTE STATEMENT ds AS USER 'REPL_FB_Lib' PASSWORD 'test' ROLE 'RDB$ADMIN';
  msg = 'id:'||id;
  SUSPEND;
END
^
ROLLBACK^

EXECUTE BLOCK
AS
BEGIN
  IF((SELECT COUNT(*) FROM dll_test)<>1)THEN EXCEPTION LIB$DDL_Exception 'Test REPL$DLL failed';
END
^

-- Test rexecuting
EXECUTE BLOCK RETURNS(msg VARCHAR(50))
AS
DECLARE ds VARCHAR(1000);
DECLARE id INTEGER;
BEGIN
  id = -100;
  ds = 'INSERT INTO REPL$DDL(id, TimeOut, sql) VALUES('||id||', 20, ''INSERT INTO dll_test VALUES(1);'')';
  EXECUTE STATEMENT ds AS USER 'REPL_FB_Lib' PASSWORD 'test' ROLE 'RDB$ADMIN';
  msg = 'id:'||id;
  SUSPEND;
END
^
DELETE FROM dll_test^
COMMIT^

-- Test no disconect for normal user
INSERT INTO REPL$DDL(sql,Disconnect_After) VALUES('INSERT INTO dll_test VALUES(1);',1)^

SET TERM ;^
COMMIT;

